// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TestFonctionnelDeposerAnnonce', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TestFonctionnelDeposerAnnonce', async function() {
    // Test name: TestFonctionnelDeposerAnnonce
    // Step # | name | target | value
    // 1 | open | /UserPage/AddSection | 
    await driver.get("http://localhost:3000/UserPage/AddSection")
    // 2 | setWindowSize | 1382x736 | 
    await driver.manage().window().setRect({ width: 1382, height: 736 })
    // 3 | click | name=titre | 
    await driver.findElement(By.name("titre")).click()
    // 4 | type | name=titre | annonce test
    await driver.findElement(By.name("titre")).sendKeys("annonce test")
    // 5 | click | name=categorie | 
    await driver.findElement(By.name("categorie")).click()
    // 6 | type | name=categorie | Bungalow
    await driver.findElement(By.name("categorie")).sendKeys("Bungalow")
    // 7 | click | name=type | 
    await driver.findElement(By.name("type")).click()
    // 8 | type | name=type | Vente
    await driver.findElement(By.name("type")).sendKeys("Vente")
    // 9 | click | name=surface | 
    await driver.findElement(By.name("surface")).click()
    // 10 | type | name=surface | 40000
    await driver.findElement(By.name("surface")).sendKeys("40000")
    // 11 | click | name=prix | 
    await driver.findElement(By.name("prix")).click()
    // 12 | type | name=prix | 1000000
    await driver.findElement(By.name("prix")).sendKeys("1000000")
    // 13 | click | css=.lg\3Agrid | 
    await driver.findElement(By.css(".lg\\3Agrid")).click()
    // 14 | click | name=wilaya | 
    await driver.findElement(By.name("wilaya")).click()
    // 15 | type | name=wilaya | Alger
    await driver.findElement(By.name("wilaya")).sendKeys("Alger")
    // 16 | click | name=commune | 
    await driver.findElement(By.name("commune")).click()
    // 17 | type | name=commune | Casbah
    await driver.findElement(By.name("commune")).sendKeys("Casbah")
    // 18 | click | css=.md\3Aw-\[400px\] | 
    await driver.findElement(By.css(".md\\3Aw-\\[400px\\]")).click()
    // 19 | type | css=.md\3Aw-\[400px\] | Description test
    await driver.findElement(By.css(".md\\3Aw-\\[400px\\]")).sendKeys("Description test")
    // 20 | click | css=.bg-\[\#4285F4\] | 
    await driver.findElement(By.css(".bg-\\[\\#4285F4\\]")).click()
    // 21 | click | css=.fa-solid | 
    await driver.findElement(By.css(".fa-solid")).click()
    // 22 | click | linkText=Mes annonces | 
    await driver.findElement(By.linkText("Mes annonces")).click()
  })
})
