# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestFonctionnelDeposerAnnonce():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testFonctionnelDeposerAnnonce(self):
    # Test name: TestFonctionnelDeposerAnnonce
    # Step # | name | target | value
    # 1 | open | /UserPage/AddSection | 
    self.driver.get("http://localhost:3000/UserPage/AddSection")
    # 2 | setWindowSize | 1382x736 | 
    self.driver.set_window_size(1382, 736)
    # 3 | click | name=titre | 
    self.driver.find_element(By.NAME, "titre").click()
    # 4 | type | name=titre | annonce test
    self.driver.find_element(By.NAME, "titre").send_keys("annonce test")
    # 5 | click | name=categorie | 
    self.driver.find_element(By.NAME, "categorie").click()
    # 6 | type | name=categorie | Bungalow
    self.driver.find_element(By.NAME, "categorie").send_keys("Bungalow")
    # 7 | click | name=type | 
    self.driver.find_element(By.NAME, "type").click()
    # 8 | type | name=type | Vente
    self.driver.find_element(By.NAME, "type").send_keys("Vente")
    # 9 | click | name=surface | 
    self.driver.find_element(By.NAME, "surface").click()
    # 10 | type | name=surface | 40000
    self.driver.find_element(By.NAME, "surface").send_keys("40000")
    # 11 | click | name=prix | 
    self.driver.find_element(By.NAME, "prix").click()
    # 12 | type | name=prix | 1000000
    self.driver.find_element(By.NAME, "prix").send_keys("1000000")
    # 13 | click | css=.lg\3Agrid | 
    self.driver.find_element(By.CSS_SELECTOR, ".lg\\3Agrid").click()
    # 14 | click | name=wilaya | 
    self.driver.find_element(By.NAME, "wilaya").click()
    # 15 | type | name=wilaya | Alger
    self.driver.find_element(By.NAME, "wilaya").send_keys("Alger")
    # 16 | click | name=commune | 
    self.driver.find_element(By.NAME, "commune").click()
    # 17 | type | name=commune | Casbah
    self.driver.find_element(By.NAME, "commune").send_keys("Casbah")
    # 18 | click | css=.md\3Aw-\[400px\] | 
    self.driver.find_element(By.CSS_SELECTOR, ".md\\3Aw-\\[400px\\]").click()
    # 19 | type | css=.md\3Aw-\[400px\] | Description test
    self.driver.find_element(By.CSS_SELECTOR, ".md\\3Aw-\\[400px\\]").send_keys("Description test")
    # 20 | click | css=.bg-\[\#4285F4\] | 
    self.driver.find_element(By.CSS_SELECTOR, ".bg-\\[\\#4285F4\\]").click()
    # 21 | click | css=.fa-solid | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-solid").click()
    # 22 | click | linkText=Mes annonces | 
    self.driver.find_element(By.LINK_TEXT, "Mes annonces").click()
  
